### PR TITLE
chore: upgrade spectrum express icons

### PR DESCRIPTION
**Pull request by Rocss**
## Description

Upgraded `@a4u/a4u-spectrum-express-open-source` to v5.0.0 and ran `npm install`.
Ran `yarn run build-icons` and `yarn run build` to generate icons.

## Related Issue

N/A

## Motivation and Context

This upgrade fixes a typo between Spectrum and Spectrum Express for the "full screen" icon. Now in both themes, the icon is named `FullScreen`.
Screenshot 2024-03-06 at 16 59 00

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Rocss** [comment]
@Hinschmi may I please get a review on this? Thanks!

**Review by Hinschmi — CHANGES_REQUESTED** [review]
I guess we have to correct the chevron and the express notification icons in the A4U package before merging.

**Review by Hinschmi — APPROVED** [review]
Looking good to me

**Comment by jianliao** [comment]
Hi @Hinschmi, since this PR include the changes for the other two open source  packages. Should we also publish the new version for them?

**Pull request merged**
